# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network "public_network", bridge: "enp3s0" 
    config.vm.network  "forwarded_port", guest: 5000, host: 5000
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "start.yml"
    end
  end