# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "deploy"
    config.vm.network  "forwarded_port", guest: 5000, host: 5000
    config.vm.provider "virtualbox" do |deploy|
      deploy.memory = 2048
      deploy.cpus = 1
    end
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "start.yml"
    end
  end